# This file was generated by GoReleaser. DO NOT EDIT.
cask "pad" do
  version "0.16.1"

  on_macos do
    on_intel do
      sha256 "31d26e469512665b92d557380744f1ffdaa9cc99d1959412afe22cd0a1fb1e00"
      url "https://github.com/PerpetualSoftware/pad/releases/download/v#{version}/pad_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "89547774b4775f6b1e6867c783211675a28290bfa808b67238d5e03559c37c6d"
      url "https://github.com/PerpetualSoftware/pad/releases/download/v#{version}/pad_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "99d0a50fedaff956388f347371b9dd4cbe2f0976ad42bc33a7cfc9988a0cbaa4"
      url "https://github.com/PerpetualSoftware/pad/releases/download/v#{version}/pad_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2b18bcbec2ef144098bc9b3568365886f3844c887efc50d75b0fbc6377376f9c"
      url "https://github.com/PerpetualSoftware/pad/releases/download/v#{version}/pad_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pad"
  desc "Project Management for the agent era"
  homepage "https://getpad.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pad"

  # No zap stanza required

end
