# This file was generated by GoReleaser. DO NOT EDIT.
cask "pad" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "8ddcbe424c2b0e6383db62db225bcff70dd11609f13f87eaf18e2e3a3e0fc42f"
      url "https://github.com/PerpetualSoftware/pad/releases/download/v#{version}/pad_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c65bf8e0cbfb41fd23b95e25578fb84b2c8cd237bf83b46693ba3248de9d9399"
      url "https://github.com/PerpetualSoftware/pad/releases/download/v#{version}/pad_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fe21644667bb244db00a45a15ad2ad101c020de435403e102ecf3c78b07366f7"
      url "https://github.com/PerpetualSoftware/pad/releases/download/v#{version}/pad_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "65f8774cca23a1a8fbcddb695ea475772838443cd5cb097b996a4edcd0d284e2"
      url "https://github.com/PerpetualSoftware/pad/releases/download/v#{version}/pad_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pad"
  desc "Project Management for the agent era"
  homepage "https://getpad.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pad"

  # No zap stanza required

end
