# This file was generated by GoReleaser. DO NOT EDIT.
cask "pad" do
  version "0.1.0-rc.6"

  on_macos do
    on_intel do
      sha256 "f336185e397bd2b82e7ecb610cf4c9aa7f0bc20b31b573f40f4961fbb732ff43"
      url "https://github.com/PerpetualSoftware/pad/releases/download/v#{version}/pad_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5e956a1338cb3f0868b0d9358cffce2bb6a401d554dc8ee316afeaf46c1b87db"
      url "https://github.com/PerpetualSoftware/pad/releases/download/v#{version}/pad_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3660bc537585fe6de91709a66cc47b50e6da7c50eb0132363ffcda7139159ed4"
      url "https://github.com/PerpetualSoftware/pad/releases/download/v#{version}/pad_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6e774ff3c79e2d26cb35b594dec481a6ea44a025357d64d4dd391e1e2df01c7b"
      url "https://github.com/PerpetualSoftware/pad/releases/download/v#{version}/pad_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pad"
  desc "Project Management for the agent era"
  homepage "https://getpad.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pad"

  # No zap stanza required

end
